CoursewareIT/Areas/admin/Controllers/PostsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoursewareIT.Areas.admin.ViewModel;
using CoursewareIT.Infrastructure;
using CoursewareIT.Models;

namespace CoursewareIT.Areas.admin.Controllers
{
    [Authorize(Roles = "author,admin,owner")]
    public class PostsController : Controller
    {
        [SelectedTab("dashboard")]
        // GET: admin/Posts
        public ActionResult Index()
        {
            using (var db = new CourseWareContext())
            {
                return View(new PostsIndex()
                {
                    Posts = db.Post.ToList()
                });
            }
        }

        [SelectedTab("posts")]
        public ActionResult ViewPosts()
        {
            var db=new CourseWareContext();
            return View(new PostsViewPosts
            {
                Posts = db.Post.ToList()
            });
        }

        [SelectedTab("new")]
        public ActionResult New()
        {
            return View("Form",new PostsForm
            {
                IsNew = true
            });
        }

        [SelectedTab("new")]
        public ActionResult Edit(int id)
        {
            var db=new CourseWareContext();
            var post = db.Post.Find(id);
            if (post == null)
                return HttpNotFound();


            return View("Form",new PostsForm
            {
                IsNew = false,
                Content = post.Body,
                PostId = post.PostId,
                Title = post.Title
            });
        }

        [HttpPost]
        public ActionResult Form(PostsForm post, HttpPostedFileBase img)
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var db=new CourseWareContext())
            {
                var post = db.Post.Find(id);
                if (post==null)
                return HttpNotFound();

                db.Post.Remove(post);
                db.SaveChanges();
            }

            return RedirectToAction("ViewPosts");
        }


    }
}

CoursewareIT/Areas/admin/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CoursewareIT.Areas.admin.ViewModel;
using CoursewareIT.Infrastructure;
using CoursewareIT.Models;

namespace CoursewareIT.Areas.admin.Controllers
{
    [Authorize(Roles = "admin,owner")]
    [SelectedTab("users")]
    public class UsersController : Controller
    {

        // GET: admin/Users
        public ActionResult Index()
        {
            var db = new CourseWareContext();
            if (User.IsInRole("owner"))
            {
                return View(new UsersIndex()
                {
                    Users = db.User.ToList()
                });
            }
            return View(new UsersIndex()
            {
                Users = db.User.Where(u => !u.Roles.Contains(db.Role.FirstOrDefault(x => x.RoleName == "admin"))).ToList()
            });
        }


        public ActionResult EditRoles(int id)
        {
            using (var db = new CourseWareContext())
            {
                var user = db.User.Find(id);
                if (user == null)
                    return HttpNotFound();

                var roles = db.Role.Where(x=>x.RoleName!="owner").ToList();

                if (!User.IsInRole("owner"))
                {
                    roles = roles.Where(role => role.RoleName == "author" || role.RoleName == "user").ToList();
                }

                return View(new EditRoles
                {
                    Roles = roles.Select(x => new RoleCheckBox
                    {
                        Id = x.RoleId,
                        IsChecked = user.Roles.Contains(x),
                        Name = x.RoleName
                    }).ToList()
                });
            }
        }

        [HttpPost]
        public ActionResult EditRoles(int id, EditRoles form)
        {
            using (var db = new CourseWareContext())
            {
                var user = db.User.Find(id);
                var roles = user.Roles.ToList();
                var selectedRoles = new List<Role>();


                foreach (var role in db.Role.ToList())
                {
                    var checkbox = form.Roles.SingleOrDefault(c => c.Id == role.RoleId);

                    if (checkbox != null)
                    {
                        if (checkbox.IsChecked)
                        {
                            selectedRoles.Add(role);
                        }
                    }
                }

                foreach (var toAdd in selectedRoles.Where(t => !roles.Contains(t)))
                    roles.Add(toAdd);


                foreach (var toRemove in roles.Where(t => !selectedRoles.Contains(t)).ToList())
                    roles.Remove(toRemove);

                user.Roles = roles;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

CoursewareIT/Areas/admin/Views/Shared/_Layout.cshtml
@helper SelectedTabClass(string selectedTab)
{
    if (selectedTab == ViewBag.SelectedTab)
    {
        @:active
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Panel</title>
    @Styles.Render("~/Content/admin/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button id="#menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <i class="fa fa-th-list fa-2x" style="color: #212121;"></i>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Posts")">C<i class="fa fa-globe"></i>URSE WARE</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home", new {area = ""})">@CoursewareIT.Resources.Main.BackToWebsite</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div id="wrapper">

        <!--        Sidebar-wrapper-->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" id="#menu">
                <li class="@SelectedTabClass("dashboard")">
                    <a href="@Url.Action("Index","Posts")">
                        <span class="fa-stack fa-lg pull-left"><i class="fa fa-archive fa-stack-1x "></i></span>
                        Dashboard
                    </a>
                </li>
                <li class="@SelectedTabClass("users")">
                    <a href="@Url.Action("Index","Users")">
                        <span class="fa-stack fa-lg pull-left"><i class="fa fa-user fa-stack-1x "></i></span>
                        @CoursewareIT.Resources.Main.Users
                    </a>
                </li>
                <li class="@SelectedTabClass("posts")">
                    <a href="@Url.Action("ViewPosts", "Posts")">
                        <span class="fa-stack fa-lg pull-left">
                            <i class="fa fa-file-text fa-stack-1x "></i>
                        </span>@CoursewareIT.Resources.Main.Posts
                    </a>
                </li>
                <li class="@SelectedTabClass("new")">
                    <a href="@Url.Action("New","Posts")"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-newspaper-o fa-stack-1x "></i></span>@CoursewareIT.Resources.Main.PostNewEdit</a>
                </li>
                @*<li>
                    <a href="#">
                        <span class="fa-stack fa-lg pull-left">
                            <i class="fa fa-youtube-play fa-stack-1x "></i>
                        </span>About
                    </a>
                </li>
                <li>
                    <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-wrench fa-stack-1x "></i></span>Services</a>
                </li>
                <li>
                    <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>Contact</a>
                </li>*@
            </ul>
        </div>
        <!--        End Sidebar-wrapper-->
        <!--Page-content-Wrapper -->
        <div id="page-content-wrapper">
            @RenderBody()
        </div>
        <!--    End Page-content-Wrapper-->
    </div>
    @*<br />

    <br />
    <footer class="text-center ">


        <h5><strong>MOUTASEM ABDULLATIF</strong><br />G140910075</h5>
    </footer>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/admin/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>